# Generated by Django 5.2.6 on 2025-11-07 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_id',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_obj_id',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='uncknown city', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='uncknown country', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='is_vailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_id'], name='idx_property_id'),
        ),
    ]
