# Generated by Django 5.2.6 on 2025-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_user_managers_remove_property_idx_property_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_vailable',
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
