# Generated by Django 5.2.6 on 2025-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_property_is_vailable_property_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_requested',
            field=models.BooleanField(default=False),
        ),
    ]
