#!/bin/bash

APP_PORT=${PORT:-8087}

set -e
set -x

cd /app
source /venv/bin/activate

echo "Waiting for Postgres at ${DB_HOST}:${DB_PORT}..."

until pg_isready -h "${DB_HOST}" -p "${DB_PORT}" >/dev/null 2>&1; do
    echo "Waiting for Postgres..."
    sleep 1
done

echo "Postgres is ready!"
echo "Running migrations..."

if [ -f /app/migrate ]; then
    echo "Running migrations..."
    bash /app/migrate
fi


/venv/bin/gunicorn --worker-tmp-dir /dev/shm alx_travel_app:application --bind "0.0.0.0:${APP_PORT}"
